name: make-lint

on: push

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2

      - name: make commands
      - uses: softwalls/frontend-project-lvl1
      - run: make lint